import Head from "next/head";
import Intro from "../components/Intro";
import Services from "../components/Services";
import Testimonials from "../components/Testimonials";
import { data } from "../data";
import styles from "../styles/Home.module.css";

export default function Home({ services }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Agency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services services={services} />
      <Testimonials />
    </div>
  );
}

// Fetch the data from an API
export const getStaticProps = async () => {
  // const services = await fetch(API)
  const services = data;
  return {
    props: { services },
  };
};
